apiVersion: apps/v1
kind: Deployment
metadata:
  name: revision-app
  labels:
    app: revision-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: revision-app
  template:
    metadata:
      labels:
        app: revision-app
    spec:
      containers:
        - name: revision-app
          image: ghcr.io/saminoua/revision-app:v1.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
